In [ ]:
from pyspark.sql import SparkSession
import pyspark.sql.functions as F

# Inicializar la sesión de Spark conectada a tu cluster de Docker solo si contamos con los recursos necesarios
spark = SparkSession.builder \
    .appName("Soundwave-Analytics-Exploration") \
    .master("spark://spark-master:7077") \
    .config("spark.jars.packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0") \
    .getOrCreate()

# Leer los datos de la capa Bronze en HDFS
path_bronze = "hdfs://namenode:9000/data/bronze/play_events"
df_bronze = spark.read.parquet(path_bronze)

# Ver las primeras filas formateadas como tabla limpia
df_bronze.show(5, truncate=False)

In [3]:
from pyspark.sql import SparkSession
import pyspark.sql.functions as F

spark = SparkSession.builder \
    .appName("Soundwave-Analytics-Exploration") \
    .master("local[*]") \
    .config("spark.jars.packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0") \
    .getOrCreate()

In [4]:
path_bronze = "hdfs://namenode:9000/data/bronze/play_events"
df_bronze = spark.read.parquet(path_bronze)

# Esto debería imprimir las primeras 5 filas en formato texto casi de inmediato
df_bronze.show(5, truncate=False)

+------------------------------------+-------------+------------------------------------+------------------------------------+--------------------------------+------------------+--------------+-------------+--------+---------+-----------------------+-----------------------+-------+
|event_id                            |event_type   |user_id                             |track_id                            |played_at                       |duration_played_ms|source        |device_type  |latitude|longitude|kafka_ts               |bronze_at              |country|
+------------------------------------+-------------+------------------------------------+------------------------------------+--------------------------------+------------------+--------------+-------------+--------+---------+-----------------------+-----------------------+-------+
|78286cbd-69f9-4804-97f1-ca9f2bfc2884|play_complete|7c7d3287-c3aa-493c-afb0-845dda67c758|d96af1f4-764d-464a-92f8-75fe790d05ea|2026-06-18T05:27:01.902774+00:00|151788            |playlist      |desktop      |-36.3179|-59.2196 |2026-06-18 05:27:01.903|2026-06-18 05:27:30.005|AR     |
|c5efda32-9580-4a7b-bfa8-0c324536a484|like         |e6206814-b3b1-486f-b388-4ea6b8208047|79dc226d-df8b-435f-95c7-c6f7b4c855cb|2026-06-18T05:27:04.110494+00:00|207081            |radio         |mobile       |-35.9529|-58.9742 |2026-06-18 05:27:04.11 |2026-06-18 05:27:30.005|AR     |
|8c2b7b0b-3555-4ae9-983c-4c860e8be9a1|play_complete|a1c54d04-f217-4581-acb3-cfba35112b97|c0161a62-b5f3-4f41-ad73-4053ff84376b|2026-06-18T05:27:04.914476+00:00|179908            |search        |smart_speaker|-36.5716|-58.0248 |2026-06-18 05:27:04.914|2026-06-18 05:27:30.005|AR     |
|7e6a28be-0942-4432-9ea7-3379a0ad2c98|play_complete|c45fdf16-1fbc-4477-b78a-4c97c650aaef|8eb84838-e5ca-4ba3-9b90-0fce4213647d|2026-06-18T05:27:06.119437+00:00|259470            |recommendation|smart_speaker|-34.0158|-59.9844 |2026-06-18 05:27:06.119|2026-06-18 05:27:30.005|AR     |
|3b0b1c2f-0c78-4f0f-a343-a6583c2a9fff|play_complete|6332cffe-f9e4-4f00-a3db-12f52fe27d8f|1ceaf0a1-c119-4221-b087-a7a8352244b0|2026-06-18T05:27:06.520634+00:00|139405            |recommendation|desktop      |-34.4703|-58.2337 |2026-06-18 05:27:06.52 |2026-06-18 05:27:30.005|AR     |
+------------------------------------+-------------+------------------------------------+------------------------------------+--------------------------------+------------------+--------------+-------------+--------+---------+-----------------------+-----------------------+-------+
only showing top 5 rows

In [5]:
# Tomamos los primeros 10 registros y los pasamos al formato visual de Pandas
df_bronze.limit(10).toPandas()

,event_id,event_type,user_id,track_id,played_at,duration_played_ms,source,device_type,latitude,longitude,kafka_ts,bronze_at,country
0,78286cbd-69f9-4804-97f1-ca9f2bfc2884,play_complete,7c7d3287-c3aa-493c-afb0-845dda67c758,d96af1f4-764d-464a-92f8-75fe790d05ea,2026-06-18T05:27:01.902774+00:00,151788,playlist,desktop,-36.3179,-59.2196,2026-06-18 05:27:01.903,2026-06-18 05:27:30.005,AR
1,c5efda32-9580-4a7b-bfa8-0c324536a484,like,e6206814-b3b1-486f-b388-4ea6b8208047,79dc226d-df8b-435f-95c7-c6f7b4c855cb,2026-06-18T05:27:04.110494+00:00,207081,radio,mobile,-35.9529,-58.9742,2026-06-18 05:27:04.110,2026-06-18 05:27:30.005,AR
2,8c2b7b0b-3555-4ae9-983c-4c860e8be9a1,play_complete,a1c54d04-f217-4581-acb3-cfba35112b97,c0161a62-b5f3-4f41-ad73-4053ff84376b,2026-06-18T05:27:04.914476+00:00,179908,search,smart_speaker,-36.5716,-58.0248,2026-06-18 05:27:04.914,2026-06-18 05:27:30.005,AR
3,7e6a28be-0942-4432-9ea7-3379a0ad2c98,play_complete,c45fdf16-1fbc-4477-b78a-4c97c650aaef,8eb84838-e5ca-4ba3-9b90-0fce4213647d,2026-06-18T05:27:06.119437+00:00,259470,recommendation,smart_speaker,-34.0158,-59.9844,2026-06-18 05:27:06.119,2026-06-18 05:27:30.005,AR
4,3b0b1c2f-0c78-4f0f-a343-a6583c2a9fff,play_complete,6332cffe-f9e4-4f00-a3db-12f52fe27d8f,1ceaf0a1-c119-4221-b087-a7a8352244b0,2026-06-18T05:27:06.520634+00:00,139405,recommendation,desktop,-34.4703,-58.2337,2026-06-18 05:27:06.520,2026-06-18 05:27:30.005,AR
5,f7632edd-c299-4842-9316-ba0652ff1c38,play_complete,4ebf05c4-2cc3-4d07-aaa5-75556809ada9,8eb84838-e5ca-4ba3-9b90-0fce4213647d,2026-06-18T05:27:07.123273+00:00,120148,radio,smart_speaker,-33.7979,-60.3445,2026-06-18 05:27:07.123,2026-06-18 05:27:30.005,AR
6,a1f6ca1a-3ea1-40f8-a1f4-0cc3f8ccbdf8,play_complete,bfe894dd-5fb0-44e3-a9a0-39ce8c1b33bc,310185c5-2a4d-40f8-96d0-158dd49016bb,2026-06-18T05:27:07.324264+00:00,91206,radio,mobile,-35.8345,-57.7673,2026-06-18 05:27:07.324,2026-06-18 05:27:30.005,AR
7,60a97217-0996-4858-b466-5dd62f56b960,play_complete,6d38dd5b-6ca1-4188-a89c-c1872e8a02c2,74275710-948c-4b38-a730-80280e5f18cf,2026-06-18T05:27:07.927049+00:00,207287,search,desktop,-36.4979,-57.6724,2026-06-18 05:27:07.927,2026-06-18 05:27:30.005,AR
8,7a0c12b7-bdc1-426f-b2c5-68078995e9bd,play_complete,9d5712b9-038a-49ab-ae78-66d9ae4148b0,a5c073a8-1287-48a8-869c-d0f0398cb5f0,2026-06-18T05:27:08.731686+00:00,184483,radio,smart_speaker,-32.9992,-58.5953,2026-06-18 05:27:08.731,2026-06-18 05:27:30.005,AR
9,4d6fe44a-5e61-459b-806c-72df4ba69993,play_partial,66ca8748-ca21-4095-8eca-5e8649203101,fe1ca2b3-ee05-4fd8-b06a-9ea6b5d7f69b,2026-06-18T05:27:10.539008+00:00,20350,recommendation,smart_speaker,-33.0049,-58.4018,2026-06-18 05:27:10.539,2026-06-18 05:27:30.005,AR

In [27]:
# 1. Filtramos solo los eventos donde el usuario dio 'like'
# 2. Agrupamos por el ID de la canción
# 3. Contamos cuántos likes tiene cada una
# 4. Ordenamos de mayor a menor y nos quedamos con las 3 mejores

df_bronze = spark.read.parquet("hdfs://namenode:9000/data/bronze/play_events")
df_top_songs = df_bronze \
    .filter(F.col("event_type") == "like") \
    .groupBy("track_id") \
    .count() \
    .withColumnRenamed("count", "total_likes") \
    .orderBy("total_likes", ascending=False) \
    .limit(3)

# Lo pasamos a Pandas para que Jupyter lo pinte como tabla elegante
df_top_songs.toPandas()

                               track_id  total_likes
0  8559ea84-78ee-403b-86aa-12080487d507           13
1  71a69653-6386-4136-b6f1-f733e4c30ffe           12
2  038f631b-cc7e-4142-9cb1-e3411bf5fdf4           12

In [28]:
# Le dice a Spark: "Olvida todo lo que crees que sabes sobre los archivos de HDFS"
spark.catalog.clearCache()

In [53]:
# 1. Filtramos solo los eventos donde el usuario dio 'like'
# 2. Agrupamos por el ID de la canción
# 3. Contamos cuántos likes tiene cada una
# 4. Ordenamos de mayor a menor y nos quedamos con las 3 mejores
df_top_songs = df_bronze \
    .filter(F.col("event_type") == "like") \
    .groupBy("track_id") \
    .count() \
    .withColumnRenamed("count", "total_likes") \
    .orderBy("total_likes", ascending=False) \
    .limit(3)

# Lo pasamos a Pandas para que Jupyter lo pinte como tabla elegante
df_top_songs.toPandas()

                               track_id  total_likes
0  8559ea84-78ee-403b-86aa-12080487d507           15
1  038f631b-cc7e-4142-9cb1-e3411bf5fdf4           15
2  71a69653-6386-4136-b6f1-f733e4c30ffe           14

In [55]:
# 1. Filtramos solo los eventos donde el usuario dio 'like'
# 2. Agrupamos por el ID de la canción
# 3. Contamos cuántos likes tiene cada una
# 4. Ordenamos de mayor a menor y nos quedamos con las 3 mejores
df_top_songs = df_bronze \
    .filter(F.col("event_type") == "like") \
    .groupBy("track_id") \
    .count() \
    .withColumnRenamed("count", "total_likes") \
    .orderBy("total_likes", ascending=False) \
    .limit(3)

# Lo pasamos a Pandas para que Jupyter lo pinte como tabla elegante
df_top_songs.toPandas()

                               track_id  total_likes
0  b171d536-fdf7-43af-94ec-7b14177accb0           15
1  71a69653-6386-4136-b6f1-f733e4c30ffe           15
2  8559ea84-78ee-403b-86aa-12080487d507           15

In [54]:
# 1. Forzamos la lectura limpia especificando el formato parquet explícitamente
df_bronze = spark.read.format("parquet").load("hdfs://namenode:9000/data/bronze/play_events")

# 2. Volvemos a lanzar la consulta del Top 3 de Likes
df_top_songs = df_bronze \
    .filter(F.col("event_type") == "like") \
    .groupBy("track_id") \
    .count() \
    .withColumnRenamed("count", "total_likes") \
    .orderBy("total_likes", ascending=False) \
    .limit(3)

# 3. Mostrar la tabla con datos actualizados de todos los países
df_top_songs.toPandas()

                               track_id  total_likes
0  b171d536-fdf7-43af-94ec-7b14177accb0           15
1  71a69653-6386-4136-b6f1-f733e4c30ffe           15
2  8559ea84-78ee-403b-86aa-12080487d507           15

In [44]:
# 1. Forzamos la lectura limpia especificando el formato parquet explícitamente
df_bronze = spark.read.format("parquet").load("hdfs://namenode:9000/data/bronze/play_events")

# 2. Volvemos a lanzar la consulta del Top 3 de Likes
df_top_songs = df_bronze \
    .filter(F.col("event_type") == "like") \
    .groupBy("track_id") \
    .count() \
    .withColumnRenamed("count", "total_likes") \
    .orderBy("total_likes", ascending=False) \
    .limit(3)

# 3. Mostrar la tabla con datos actualizados de todos los países
df_top_songs.toPandas()

                               track_id  total_likes
0  8559ea84-78ee-403b-86aa-12080487d507           15
1  71a69653-6386-4136-b6f1-f733e4c30ffe           14
2  b171d536-fdf7-43af-94ec-7b14177accb0           13

In [34]:
# Ver cuántos eventos hay por cada país en tiempo real
df_bronze.groupBy("country").count().orderBy("count", ascending=False).toPandas()

  country  count
0      ES   2835
1      AR   2803
2      BR   2800
3      CL   2786
4      CO   2776
5      MX   2719
6      US   2698
7      PE   2669

In [43]:
# Ver cuántos eventos hay por cada país en tiempo real
df_bronze.groupBy("country").count().orderBy("count", ascending=False).toPandas()

  country  count
0      ES   2887
1      AR   2857
2      BR   2846
3      CL   2843
4      CO   2842
5      MX   2776
6      US   2750
7      PE   2731

In [40]:
# Cuenta cuántos eventos totales hay de cada tipo en toda tu base de datos
df_bronze.groupBy("event_type").count().toPandas()

      event_type  count
0   play_partial   2217
1  play_complete  14614
2           skip   4539
3           like   1162

In [50]:
# Cuenta cuántos eventos totales hay de cada tipo en toda tu base de datos
df_bronze.groupBy("event_type").count().orderBy("count", ascending=True).toPandas()

      event_type  count
0           like   1225
1   play_partial   2351
2           skip   4805
3  play_complete  15490